# Generated by Django 2.2.12 on 2022-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=30)),
                ('titula', models.CharField(max_length=10)),
                ('predgovor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clanstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dugovanje', models.BooleanField(default=False)),
                ('odobrenje_posudbe', models.BooleanField(default=True)),
                ('trajanje_clanstva', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dobna_skupina', models.CharField(max_length=20)),
                ('edukativna_namjena', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('sadrzaj', models.TextField()),
                ('izdavanje', models.DateTimeField(verbose_name='datum izdavanja')),
                ('nakladnik', models.CharField(max_length=40)),
                ('dostupnost', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanr', models.CharField(choices=[('DF', 'Djecja fikcija'), ('RO', 'Romantika'), ('ZF', 'Znanstvena fantastika'), ('TH', 'Triler ili horor'), ('BI', 'Biografija ili autobiografija'), ('MO', 'Motivacijske knjige'), ('ST', 'Strip')], default='BI', max_length=2)),
            ],
        ),
    ]
