# Generated by Django 3.2.12 on 2023-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_knjiga_zanrovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='zanrovi',
            field=models.ManyToManyField(to='main.zanr'),
        ),
    ]
